### ISSUE TITLE
[Bug] NPC Actors / Adversaries CSS Issue

### ISSUE THREAD

**Issue by Gensokian** [featureJosh/daggerheart-swb#8]
There seems to be a small CSS issue with the adversaries Profile image
![screenshot](https://dl.james-things.com/u/adorable-ideal-arabianwildcat.jpg)

A small CSS Fix by Wisdom of Wombats
```css
/* Custom CSS */

.item .sheet-header .profile-img {
    z-index: -500;
}

.item .sheet-header .header-fields {
    padding-top: 140px;
    padding-bottom: 0px !important; 
    border: none;
}

.item .sheet-header .item-charname input {
    line-height: 0.9;
}

.item nav.sheet-tabs.tabs {
    margin-top: 0.1em;
}
```
